name: export-kicad-documents
run-name: Export KiCAD Documents
on: [push]

jobs:
  export-documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Getting KiCAD Docker container
        run: docker pull kicad/kicad:nightly-full

      - name: Exporting KiCAD PDFs
        run: |
          EXPORT_PATH="./hardware/outputs"
          mkdir -p $EXPORT_PATH
          KICAD_PROJECTS=$(find . -name *.kicad_pro)
          PROJECT_PATH=${KICAD_PROJECTS[0]%.kicad_pro}
          SCHEMATIC_PATH="${PROJECT_PATH}.kicad_sch"
          PCB_PATH="${PROJECT_PATH}.kicad_pcb"

          docker run \
          -u $(id -u):$(id -g) \
          -v $(pwd):/workspace \
          -w /workspace \
          kicad/kicad:nightly-full \
          kicad-cli sch export pdf $SCHEMATIC_PATH -o "${EXPORT_PATH}/schematics.pdf"

      - name: Upload PDFs
        uses: actions/upload-artifact@v6
        with:
          name: Schematics
          path: "${EXPORT_PATH}/schematics.pdf"